this.NS = 'TEN';

this.TYPE_ELEMENT_NODE = 1;
this.TYPE_TEXT_NODE = 3;
this.TYPE_CDATA_SECTION_NODE = 4;
this.TYPE_COMMENT_NODE = 8;
this.TYPE_DOCUMENT_NODE = 9;

this.STATE_TEXT = 1;
this.STATE_CODE = 2;

this.TEMPLATE_TYPE_TEXT = 1;
this.TEMPLATE_TYPE_CODE = 2;
this.TEMPLATE_TYPE_INHERIT = 3;